organization: <organization name> # exapmle - example.com

assets:
  - type: ip
    value: <ip> # example - 8.8.8.8

  - type: ip
    value: <ip>  # example - 1.1.1.1

  - type: cidr
    value: <example ip>/24
